"""
Mock Nano-vLLM implementation for development and testing.
This provides the same API as Nano-vLLM but with mock responses.
"""

__version__ = "0.2.0-mock"


class SamplingParams:
    def __init__(self, temperature=0.7, top_p=0.9, max_tokens=512):
        self.temperature = temperature
        self.top_p = top_p
        self.max_tokens = max_tokens


class LLM:
    def __init__(self, model, **kwargs):
        self.model = model
        self.kwargs = kwargs
        print(f"Mock LLM initialized with model: {model}")

    def generate(self, prompts, sampling_params):
        """Generate mock responses."""
        responses = []
        for prompt in prompts:
            response = {
                "text": f"Mock response to: {prompt[:50]}... (Generated by Mock Nano-vLLM)",
                "prompt": prompt,
                "model": self.model,
            }
            responses.append(response)
        return responses
