#!/usr/bin/env bash
# Constitutional Hash: cdd01ef066bc6cf2
# ACGS-2 Constitutional Compliance Validation
CONSTITUTIONAL_HASH="cdd01ef066bc6cf2"


set -e

cd "$(dirname "$0")/.."

echo "==> Running Go build"
go build ./...
