// Constitutional Hash: cdd01ef066bc6cf2

/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

/// <reference path="../../sst-env.d.ts" />

import "sst"
export {}
